### ISSUE TITLE
Let's finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s1-evaluacion-intermedia-japocoinyenhoang#1]
Good job @japocoinyenhoang 
Here you have some tips to improve the exercise:
- [x] Download the Adalab logo to a proper folder (although it is ok to use an absolute path we are going to use relative paths to a project file)
- [x] Should the `.menu` element be a nonsemantics `div` or a rich semantic `nav` (commonly used for our main navigation)
- [x] There are some weird margins, let's remove them:
  - [x] Remember the browser add some margins to the `<body>` element
  - [x] Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Main section should fit 100% of browser's height
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Class selectors are free, let's use them instead tag selectors

Once you have those fixed try to finish the styles for the mobile version and then resolve the ones for the tablet version.

**Comment by japocoinyenhoang** [comment]
exercise finished.
Thanks.
